<a href="https://colab.research.google.com/github/drsubirghosh2008/drsubirghosh2008/blob/main/PW_Assignment_Module_16_26_10_24_NumpyBasic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Consider the below code to answer further questions:
import numpy as np
list_ = [ ‘1’ , ’2’ , ‘3’ , ‘4’ , ‘5’ ]
array_list = np.array(object = list_)

Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code to print the data types of both the variables.

In [14]:
import numpy as np
list_ = [ '1','2', '3','4','5' ]
array_list = np.array(object = list_)
print(type(list_))#soln.1
print(type(array_list))#soln.1
print(list_)#soln.2
print(array_list)#soln.2

<class 'list'>
<class 'numpy.ndarray'>
['1', '2', '3', '4', '5']
['1' '2' '3' '4' '5']


There any difference in the data type of variables list_ and array_list.

Q2. Write a code to print the data type of each and every element of both the variables list_ and arra_list.

In [13]:
import numpy as np
list_ = [ '1','2', '3','4','5' ]
array_list = np.array(object = list_)
print(list_)
print(array_list)

['1', '2', '3', '4', '5']
['1' '2' '3' '4' '5']


Q3. Considering the following changes in the variable, array_list:

array_list = np.array(object = list_, dtype = int)

Will there be any difference in the data type of the elements present in both the variables, list_ and arra_list?

If so then print the data types of each and every element present in both the variables, list_ and arra_list.


In [17]:
import numpy as np
array_list = np.array(object = list_, dtype = int)
print(type(list_))
print(type(array_list))
print(list_)
print(array_list)

<class 'list'>
<class 'numpy.ndarray'>
['1', '2', '3', '4', '5']
[1 2 3 4 5]



Consider the below code to answer further questions:

import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

Q4. Write a code to find the following characteristics of variable, num_array:

(i) shape

(ii) size

In [21]:
import numpy as np

num_list = [[1, 2, 3], [4, 5, 6]]
num_array = np.array(object=num_list)

# Get the "shape" of num_list (number of sublists and their lengths)
num_list_shape = (len(num_list), len(num_list[0]))  # Assuming all sublists have the same length

# Get the shape of the NumPy array
num_array_shape = num_array.shape

# Get the total number of elements in num_list
num_list_size = sum(len(sublist) for sublist in num_list)

# Get the total number of elements in the NumPy array
num_array_size = num_array.size


print(num_list_shape) # Output: (2, 3)
print(num_array_shape) # Output: (2, 3)
print(num_list_size)   # Output: 6
print(num_array_size)   # Output: 6

(2, 3)
(2, 3)
6
6


Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array creation function.
[Hint: The size of the array will be 9 and the shape will be (3,3).]

In [29]:
import numpy as np

# Creating a 3x3 matrix of zeros
zero_matrix = np.zeros((3, 3))
print(zero_matrix)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


Q6. Create an identity matrix of shape (5,5) using numpy functions?
[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [28]:
# Importing the NumPy library with an alias 'np'
import numpy as np

# Creating a diagonal matrix with diagonal elements 1, 2, 3, 4, 5 using np.diag()
x = np.diag([1, 1, 1, 1, 1])

# Printing the diagonal matrix 'x'
print(x)


[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


**Thank You!**
